### ISSUE TITLE
Update navbar app version automatically

### ISSUE THREAD

**Issue by Soitora** [xhenos/kodo#9]
When an update occurs to Tachiyomi stable, the navbar version should preferably update automatically

Best if it happens through an action and not network-active

![image](https://github.com/xhenos/kodo/assets/10836780/ffd2ca7a-4754-4d1f-8cd6-bb318727f736)

**Comment by alessandrojean** [comment]
Just to keep it documented: the site makes usage of the data loading methods provided by VitePress, but they can only be used inside pages and components. It's missing the support to use inside other files.
